name: Dependency Scan (OWASP DepScan)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  depscan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '>=3.8'

      - name: Install OWASP DepScan
        run: pip install owasp-depscan

      - name: Run DepScan
        run: |
          depscan --src . --reports-dir ./reports

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: depscan-report
          path: reports
